// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Color struct {
	R *int32 `json:"r,omitempty"`
	G *int32 `json:"g,omitempty"`
	B *int32 `json:"b,omitempty"`
}

type Humidity struct {
	Value *float64 `json:"value,omitempty"`
}

type Orientation struct {
	Pitch *float64 `json:"pitch,omitempty"`
	Roll  *float64 `json:"roll,omitempty"`
	Yaw   *float64 `json:"yaw,omitempty"`
}

type Pressure struct {
	Value *float64 `json:"value,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type Temperature struct {
	Value *float64 `json:"value,omitempty"`
}
