// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Color struct {
	R *int32 `json:"r,omitempty"`
	G *int32 `json:"g,omitempty"`
	B *int32 `json:"b,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
